
GET http://localhost:3000/data

###
POST http://localhost:3000/data
Content-Type: application/json

{
    "a": "hubba Bubba",
    "b": "rope",
    "c": "pizza",
    "d": ["x","y","z"]
}

###
PATCH http://localhost:3000/user/65e00c98c487b8e20cfd2abe
Content-Type: application/json

{"title": "i'm patched"}

###
DELETE http://localhost:3000/user/dawg
